[ApplicationPreferences]
CurrentLocale                                     = en
EarliestChangeLog                                 = 4.38.23684
LastAuthorsListSorter_authorList_                 = sortByLastName()
LastFTEStep                                       = BEGIN
LastLibrarySorter_books_filterByAllItems%28%29    = sortByNewest()
LastLibrarySubFilter_books_filterByAllItems%28%29 = 
LastLibraryTab                                    = Books
LastLibraryViewType_author                        = viewBy5List()
LastLibraryViewType_books                         = viewBy5List()
LastLibraryViewType_series                        = viewBy5List()
LastLibraryViewType_seriesList                    = viewBy5List()
LastSyncTime                                      = @Variant(\0\0\0\x10\0%yx\0\x41\xa9\x93\x2)
LibraryViewVisitCount                             = 20
MarkAsFinishedLastShown                           = @Variant(\0\0\0\x10\0%yy\x3U\x11\xa9\xff)
MarkAsUnreadLastShown                             = @Variant(\0\0\0\x10\0%yy\x3U\x11\xaf\xff)
SideloadedMode                                    = true
StylusTipWarning                                  = true
SwipeDialogShown                                  = true
firstRunDate                                      = @Variant(\0\0\0\x10\0%yy\x2\xa2\x1e\xde\x2)
lastPlugTime                                      = @Variant(\0\0\0\x10\0%y\x80\x2\xfa\xb2.\x2)

[FeatureSettings]
ExcludeSyncFolders = (\\.(?!kobo|adobe).+|([^.][^/]*/)+\\..+)

[PowerOptions]
ColorSetting    = 3950
FrontLightLevel = 4
